"""
Obsidian vault → .prompt conversion (pbt/obsidian), and the `pbt obsidian`
commands that hand the result to the regular pbt commands.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pbt.executor.graph import build_dag, build_models_from_dict, load_models
from pbt.obsidian import ObsidianError, convert_vault, load_vault, write_models
from tests.conftest import STUB_CLIENT_PY, run_pbt


def _vault(root: Path, notes: dict[str, str]) -> Path:
    vault = root / "vault"
    for rel, text in notes.items():
        path = vault / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return vault


def test_links_become_refs_and_drive_the_dag(tmp_path: Path) -> None:
    vault = _vault(tmp_path, {
        "Research/Market Topic.md": "---\naliases: [Topic]\n---\nPick a market.\n",
        "Ideas.md": "Ideas about ![[Topic]] and [[Research/Market Topic#Heading|it]].\n",
        "Final Draft.md": "Write it up: [[ideas]]\n",
    })
    converted = convert_vault(vault)

    assert set(converted) == {"market_topic", "ideas", "final_draft"}
    assert "Ideas about {{ ref('market_topic') }} and {{ ref('market_topic') }}." in converted["ideas"].source
    assert converted["ideas"].depends_on == ["market_topic"]

    dag = build_dag(build_models_from_dict(load_vault(vault)))
    assert list(dag.predecessors("final_draft")) == ["ideas"]


def test_frontmatter_pbt_block_becomes_config(tmp_path: Path) -> None:
    vault = _vault(tmp_path, {
        "Ideas.md": "---\ntags: [x]\npbt:\n  output_format: json\n---\nList ideas.\n",
        "Expand.md": '---\npbt:\n  each: "[[Ideas]].items[*]"\n  global_instruction: false\n---\nExpand {{ each }}.\n',
        "Scratch.md": "---\npbt: false\n---\nNot a model.\n",
    })
    models = build_models_from_dict(load_vault(vault))

    assert set(models) == {"ideas", "expand"}
    assert models["ideas"].config == {"output_format": "json"}
    assert models["expand"].config == {"each": "ideas.items[*]", "global_instruction": "False"}
    assert models["expand"].depends_on == ["ideas"]


def test_code_comments_attachments_and_unresolved_links(tmp_path: Path) -> None:
    vault = _vault(tmp_path, {
        "A.md": "Keep %% drop this %%[[Missing|shown]] ![[pic.png]]\n```\n[[B]]\n```\n",
        "B.md": "b\n",
        ".obsidian/workspace.md": "[[A]]\n",
    })
    note = convert_vault(vault)["a"]

    assert "drop this" not in note.source
    assert "Keep shown ![[pic.png]]" in note.source
    assert "```\n[[B]]\n```" in note.source
    assert note.depends_on == []
    assert note.unresolved == ["Missing"]
    assert set(convert_vault(vault)) == {"a", "b"}


def test_name_collisions_and_ambiguous_links_are_errors(tmp_path: Path) -> None:
    with pytest.raises(ObsidianError, match="both become model 'note'"):
        convert_vault(_vault(tmp_path / "one", {"Note.md": "", "x/note.md": ""}))
    with pytest.raises(ObsidianError, match="matches several notes"):
        convert_vault(_vault(tmp_path / "two", {"x/Same.md": "", "y/Same Two.md": "---\naliases: [Same]\n---\n", "c.md": "[[Same]]"}))


def test_write_models_replaces_only_its_own_output(tmp_path: Path) -> None:
    vault = _vault(tmp_path, {"Sub/1_a_Brief.md": "brief\n"})
    out = tmp_path / "out"
    write_models(convert_vault(vault), out)
    (out / "stale.prompt").write_text("old", encoding="utf-8")
    write_models(convert_vault(vault), out)

    assert not (out / "stale.prompt").exists()
    assert list(load_models(out)) == ["brief"]  # sequence prefix stripped, as pbt does

    hand_written = tmp_path / "models"
    hand_written.mkdir()
    (hand_written / "mine.prompt").write_text("mine", encoding="utf-8")
    with pytest.raises(ObsidianError, match="not generated by `pbt obsidian`"):
        write_models(convert_vault(vault), hand_written)


def test_cli_obsidian_run_passes_options_through(tmp_path: Path) -> None:
    _vault(tmp_path, {
        "Topic.md": "Pick a topic.\n",
        "Article.md": "Write about [[Topic]] for {{ promptdata('audience') }}.\n",
        "Other.md": "Unrelated.\n",
    })
    (tmp_path / "client.py").write_text(STUB_CLIENT_PY, encoding="utf-8")

    result = run_pbt("obsidian", "run", "vault", "-s", "article",
                     "--promptdata", "audience=devs", cwd=tmp_path, check=False)

    assert result.returncode == 0, result.stdout + result.stderr
    assert (tmp_path / "obsidian_models" / "article.prompt").is_file()
    assert (tmp_path / "outputs" / "article.md").is_file()
    assert not (tmp_path / "outputs" / "other.md").exists()
