"""Storage backend interface used by pbt runtime code.

``mark_model_success`` stores the *raw* model output, which is what the prompt
cache serves.  When a validator transforms that output, the executor also calls
``record_validated_output`` with the transformed value, so ``pbt test`` judges
what the pipeline actually passed downstream rather than the raw text.  That
method is optional: a backend that does not define it simply keeps the raw
output, and the executor skips the call.
"""

from __future__ import annotations

from typing import Any, Protocol


class StorageBackend(Protocol):
    def init_db(self) -> None: ...
    def create_run(self, model_count: int, git_sha: str | None = None) -> str: ...
    def finish_run(self, run_id: str, status: str) -> None: ...
    def get_latest_successful_run(self) -> Any | None: ...
    def record_test_result(self, run_id: str, result: Any) -> None: ...
    def get_test_results(self, run_id: str) -> list[Any]: ...
    def get_model_outputs_from_run(self, run_id: str, model_names: list[str]) -> dict[str, str]: ...
    def get_cached_llm_output(self, cache_key: str) -> str | None: ...
    def upsert_model_pending(self, run_id: str, model_name: str, prompt_template: str, depends_on: list[str], model_type: str = "", config: dict | None = None) -> None: ...
    def mark_model_running(self, run_id: str, model_name: str) -> None: ...
    def mark_model_success(
        self,
        run_id: str,
        model_name: str,
        prompt_rendered: str,
        llm_output: str,
        cache_key: str | None = None,
        cached: bool = False,
    ) -> None: ...
    def record_validated_output(self, run_id: str, model_name: str, output: str) -> None: ...
    def mark_model_error(self, run_id: str, model_name: str, error: str) -> None: ...
    def mark_model_skipped(self, run_id: str, model_name: str) -> None: ...
    def get_run_results(self, run_id: str) -> list[Any]: ...
    def get_latest_runs(self, limit: int = 10) -> list[Any]: ...
