"""Storage backend interface used by pbt runtime code."""

from __future__ import annotations

from typing import Any, Protocol


class StorageBackend(Protocol):
    def init_db(self) -> None: ...
    def create_run(self, model_count: int, git_sha: str | None = None) -> str: ...
    def finish_run(self, run_id: str, status: str) -> None: ...
    def get_latest_successful_run(self) -> Any | None: ...
    def record_test_result(self, run_id: str, result: Any) -> None: ...
    def get_test_results(self, run_id: str) -> list[Any]: ...
    def get_model_outputs_from_run(self, run_id: str, model_names: list[str]) -> dict[str, str]: ...
    def get_cached_llm_output(self, cache_key: str) -> str | None: ...
    def upsert_model_pending(self, run_id: str, model_name: str, prompt_template: str, depends_on: list[str]) -> None: ...
    def mark_model_running(self, run_id: str, model_name: str) -> None: ...
    def mark_model_success(
        self,
        run_id: str,
        model_name: str,
        prompt_rendered: str,
        llm_output: str,
        cache_key: str | None = None,
    ) -> None: ...
    def mark_model_error(self, run_id: str, model_name: str, error: str) -> None: ...
    def mark_model_skipped(self, run_id: str, model_name: str) -> None: ...
    def get_run_results(self, run_id: str) -> list[Any]: ...
    def get_latest_runs(self, limit: int = 10) -> list[Any]: ...
